### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Darkness6030** [Susideur/moreCommands#1]
Hi. See OceanPandorum/PandorumPlugin. It has a lot of commands and features that you can add to ur plugin

**Comment by Susideur** [comment]
Thank you. I will watch

**Comment by Susideur** [comment]
There are /mute and /core that interest me.

**Comment by Susideur** [comment]
and /tell too

**Comment by Darkness6030** [comment]
Also see a timer, that shows how much time did player spend on the map

**Comment by Darkness6030** [comment]
Also /nominate, a very useful command

**Comment by Susideur** [comment]
That would be nice, but I also don't want there to be too many commands.
